### ISSUE TITLE
Sbam for Fronius Symo Hybrid ?

### ISSUE THREAD

**Issue by mxcxpx** [atbore-phx/sbam#23]
I have the previous Symo Hybrid Inverter. (not the 24)

is it possible to use this?

only thing what is different. my Symo do not have this Solar API" menu

Sbam uses the local Fronius API to retrieve data related to the battery:
Open the web interface of the inverter
Select the "Communication" section
Open the "Solar API" menu
Enable Solar API Communication

**Comment by atbore-phx** [comment]
Hi @mxcxpx,

Solar API communication is needed to retrieve battery status, so that is an important part of SBAM. I have never tested it with previous models, so I don't know if SBAM can work, even partially with your inverter. 
You also need to check if the Modbus registers are the same between the devices (this protocol is used to configure charging/discharging).

I'm open to anyone who owns a different inverter wanting to open a pull request. I can't do that because I don't have this model, sorry. :(
